name: Deploy to Webify

on:
  workflow_dispatch: {}
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke Webify Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBIFY_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
